server:
  port: 9006  # Äá»•i tÃ¹y theo service, vÃ­ dá»¥ 9006 cho chatservice

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://hdan-2:30861/eureka  # Cloud 2: Discovery Server
  instance:
    prefer-ip-address: true
    ip-address: hdan-3                       # ğŸ‘ˆ Äáº·t lÃ  IP hoáº·c tÃªn Ä‘á»‹nh danh Cloud 3 (cÃ³ trong /etc/hosts Cloud 2)
    non-secure-port: 30906                    # ğŸ‘ˆ NodePort mÃ  báº¡n expose service ra ngoÃ i
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  application:
    name: chatservice                         # ğŸ‘ˆ Äáº·t Ä‘Ãºng tÃªn service

  kafka:
    enabled: false

  config:
    import: classpath:application-common.yml

app:
  base-url: ${CLIENT_URL:http://localhost:4000/}
